apiVersion: v1  # Version de l'API Kubernetes utilisée pour cette configuration
kind: Secret  # Type de ressource Kubernetes à créer, ici un Secret
metadata:  # Métadonnées pour la ressource
  name: mongo-credentials  # Nom du Secret
  namespace: devops-demo  # Namespace dans lequel ce Secret sera créé
type: Opaque  # Type du Secret, ici Opaque pour indiquer qu'il contient des données arbitraires encodées en base64
data:  # Données du Secret, encodées en base64
  username: cm9vdA==  # Nom d'utilisateur encodé en base64 (ici "root" après décodage)
  password: dGVzdDEyMzQ=  # Mot de passe encodé en base64 (ici "test1234" après décodage)